import type { ExerciseCategory, Equipment, MovementPattern } from '@/types/enums';

interface ExerciseSeed {
  id: string;
  name: string;
  category: ExerciseCategory;
  equipment: Equipment;
  movementPattern: MovementPattern;
  defaultRepRangeMin: number;
  defaultRepRangeMax: number;
  defaultRestSeconds: number;
  muscles: { muscleGroupId: string; role: 'primary' | 'secondary'; contribution: number }[];
}

export const EXERCISES: ExerciseSeed[] = [
  // --- CHEST ---
  { id: 'ex-bb-bench', name: 'Barbell Bench Press', category: 'compound', equipment: 'barbell', movementPattern: 'horizontal_push', defaultRepRangeMin: 6, defaultRepRangeMax: 10, defaultRestSeconds: 180, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-front-delts', role: 'secondary', contribution: 0.4 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-bb-incline-bench', name: 'Incline Barbell Bench Press', category: 'compound', equipment: 'barbell', movementPattern: 'horizontal_push', defaultRepRangeMin: 6, defaultRepRangeMax: 10, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-front-delts', role: 'primary', contribution: 0.6 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-db-bench', name: 'Dumbbell Bench Press', category: 'compound', equipment: 'dumbbell', movementPattern: 'horizontal_push', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-front-delts', role: 'secondary', contribution: 0.3 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-db-incline-bench', name: 'Incline Dumbbell Bench Press', category: 'compound', equipment: 'dumbbell', movementPattern: 'horizontal_push', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-front-delts', role: 'primary', contribution: 0.5 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-cable-fly', name: 'Cable Fly', category: 'isolation', equipment: 'cable', movementPattern: 'horizontal_push', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-pec-deck', name: 'Pec Deck', category: 'isolation', equipment: 'machine', movementPattern: 'horizontal_push', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-dips', name: 'Dips', category: 'compound', equipment: 'bodyweight', movementPattern: 'vertical_push', defaultRepRangeMin: 6, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 0.7 }, { muscleGroupId: 'mg-triceps', role: 'primary', contribution: 0.6 }, { muscleGroupId: 'mg-front-delts', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-pushup', name: 'Push-Up', category: 'compound', equipment: 'bodyweight', movementPattern: 'horizontal_push', defaultRepRangeMin: 10, defaultRepRangeMax: 20, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.4 }, { muscleGroupId: 'mg-front-delts', role: 'secondary', contribution: 0.3 }] },

  // --- SHOULDERS ---
  { id: 'ex-ohp', name: 'Overhead Press', category: 'compound', equipment: 'barbell', movementPattern: 'vertical_push', defaultRepRangeMin: 6, defaultRepRangeMax: 10, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-front-delts', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-side-delts', role: 'secondary', contribution: 0.4 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.4 }] },
  { id: 'ex-db-shoulder-press', name: 'Dumbbell Shoulder Press', category: 'compound', equipment: 'dumbbell', movementPattern: 'vertical_push', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-front-delts', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-side-delts', role: 'secondary', contribution: 0.4 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-lateral-raise', name: 'Lateral Raise', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 12, defaultRepRangeMax: 20, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-side-delts', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-cable-lateral-raise', name: 'Cable Lateral Raise', category: 'isolation', equipment: 'cable', movementPattern: 'isolation', defaultRepRangeMin: 12, defaultRepRangeMax: 20, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-side-delts', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-face-pull', name: 'Face Pull', category: 'isolation', equipment: 'cable', movementPattern: 'horizontal_pull', defaultRepRangeMin: 12, defaultRepRangeMax: 20, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-rear-delts', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-upper-back', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-reverse-fly', name: 'Reverse Fly', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 12, defaultRepRangeMax: 20, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-rear-delts', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-front-raise', name: 'Front Raise', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-front-delts', role: 'primary', contribution: 1.0 }] },

  // --- BACK ---
  { id: 'ex-bb-row', name: 'Barbell Row', category: 'compound', equipment: 'barbell', movementPattern: 'horizontal_pull', defaultRepRangeMin: 6, defaultRepRangeMax: 10, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-upper-back', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-lats', role: 'primary', contribution: 0.7 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.3 }, { muscleGroupId: 'mg-rear-delts', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-db-row', name: 'Dumbbell Row', category: 'compound', equipment: 'dumbbell', movementPattern: 'horizontal_pull', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-lats', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-upper-back', role: 'primary', contribution: 0.6 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-pullup', name: 'Pull-Up', category: 'compound', equipment: 'bodyweight', movementPattern: 'vertical_pull', defaultRepRangeMin: 5, defaultRepRangeMax: 12, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-lats', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.4 }, { muscleGroupId: 'mg-upper-back', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-lat-pulldown', name: 'Lat Pulldown', category: 'compound', equipment: 'cable', movementPattern: 'vertical_pull', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-lats', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.3 }, { muscleGroupId: 'mg-upper-back', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-cable-row', name: 'Seated Cable Row', category: 'compound', equipment: 'cable', movementPattern: 'horizontal_pull', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-upper-back', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-lats', role: 'primary', contribution: 0.7 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-tbar-row', name: 'T-Bar Row', category: 'compound', equipment: 'barbell', movementPattern: 'horizontal_pull', defaultRepRangeMin: 6, defaultRepRangeMax: 10, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-upper-back', role: 'primary', contribution: 0.9 }, { muscleGroupId: 'mg-lats', role: 'primary', contribution: 0.6 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-chinup', name: 'Chin-Up', category: 'compound', equipment: 'bodyweight', movementPattern: 'vertical_pull', defaultRepRangeMin: 5, defaultRepRangeMax: 12, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-lats', role: 'primary', contribution: 0.9 }, { muscleGroupId: 'mg-biceps', role: 'primary', contribution: 0.6 }, { muscleGroupId: 'mg-upper-back', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-deadlift', name: 'Deadlift', category: 'compound', equipment: 'barbell', movementPattern: 'hip_hinge', defaultRepRangeMin: 3, defaultRepRangeMax: 6, defaultRestSeconds: 240, muscles: [{ muscleGroupId: 'mg-hamstrings', role: 'primary', contribution: 0.7 }, { muscleGroupId: 'mg-glutes', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-lower-back', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-upper-back', role: 'secondary', contribution: 0.4 }, { muscleGroupId: 'mg-quads', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-rack-pull', name: 'Rack Pull', category: 'compound', equipment: 'barbell', movementPattern: 'hip_hinge', defaultRepRangeMin: 3, defaultRepRangeMax: 6, defaultRestSeconds: 210, muscles: [{ muscleGroupId: 'mg-upper-back', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-lower-back', role: 'primary', contribution: 0.7 }, { muscleGroupId: 'mg-traps', role: 'secondary', contribution: 0.5 }, { muscleGroupId: 'mg-glutes', role: 'secondary', contribution: 0.4 }] },
  { id: 'ex-shrug', name: 'Barbell Shrug', category: 'isolation', equipment: 'barbell', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-traps', role: 'primary', contribution: 1.0 }] },

  // --- ARMS ---
  { id: 'ex-bb-curl', name: 'Barbell Curl', category: 'isolation', equipment: 'barbell', movementPattern: 'isolation', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-biceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-db-curl', name: 'Dumbbell Curl', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-biceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-hammer-curl', name: 'Hammer Curl', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-biceps', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-forearms', role: 'secondary', contribution: 0.5 }] },
  { id: 'ex-incline-curl', name: 'Incline Dumbbell Curl', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-biceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-preacher-curl', name: 'Preacher Curl', category: 'isolation', equipment: 'barbell', movementPattern: 'isolation', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-biceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-cable-curl', name: 'Cable Curl', category: 'isolation', equipment: 'cable', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-biceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-close-grip-bench', name: 'Close-Grip Bench Press', category: 'compound', equipment: 'barbell', movementPattern: 'horizontal_push', defaultRepRangeMin: 6, defaultRepRangeMax: 10, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-triceps', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-chest', role: 'secondary', contribution: 0.5 }] },
  { id: 'ex-skull-crusher', name: 'Skull Crusher', category: 'isolation', equipment: 'barbell', movementPattern: 'isolation', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-triceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-tricep-pushdown', name: 'Tricep Pushdown', category: 'isolation', equipment: 'cable', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-triceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-overhead-ext', name: 'Overhead Tricep Extension', category: 'isolation', equipment: 'cable', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-triceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-wrist-curl', name: 'Wrist Curl', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 15, defaultRepRangeMax: 25, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-forearms', role: 'primary', contribution: 1.0 }] },

  // --- LEGS ---
  { id: 'ex-squat', name: 'Barbell Squat', category: 'compound', equipment: 'barbell', movementPattern: 'squat', defaultRepRangeMin: 5, defaultRepRangeMax: 8, defaultRestSeconds: 210, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-glutes', role: 'primary', contribution: 0.7 }, { muscleGroupId: 'mg-hamstrings', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-front-squat', name: 'Front Squat', category: 'compound', equipment: 'barbell', movementPattern: 'squat', defaultRepRangeMin: 5, defaultRepRangeMax: 8, defaultRestSeconds: 180, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-glutes', role: 'secondary', contribution: 0.5 }] },
  { id: 'ex-leg-press', name: 'Leg Press', category: 'compound', equipment: 'machine', movementPattern: 'squat', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 0.9 }, { muscleGroupId: 'mg-glutes', role: 'secondary', contribution: 0.5 }] },
  { id: 'ex-hack-squat', name: 'Hack Squat', category: 'compound', equipment: 'machine', movementPattern: 'squat', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-glutes', role: 'secondary', contribution: 0.4 }] },
  { id: 'ex-leg-ext', name: 'Leg Extension', category: 'isolation', equipment: 'machine', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-lunge', name: 'Dumbbell Lunge', category: 'compound', equipment: 'dumbbell', movementPattern: 'lunge', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-glutes', role: 'primary', contribution: 0.7 }] },
  { id: 'ex-bulgarian-split', name: 'Bulgarian Split Squat', category: 'compound', equipment: 'dumbbell', movementPattern: 'lunge', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 0.9 }, { muscleGroupId: 'mg-glutes', role: 'primary', contribution: 0.7 }] },
  { id: 'ex-rdl', name: 'Romanian Deadlift', category: 'compound', equipment: 'barbell', movementPattern: 'hip_hinge', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-hamstrings', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-glutes', role: 'primary', contribution: 0.7 }, { muscleGroupId: 'mg-lower-back', role: 'secondary', contribution: 0.4 }] },
  { id: 'ex-leg-curl', name: 'Leg Curl', category: 'isolation', equipment: 'machine', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-hamstrings', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-hip-thrust', name: 'Hip Thrust', category: 'compound', equipment: 'barbell', movementPattern: 'hip_hinge', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-glutes', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-hamstrings', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-calf-raise', name: 'Standing Calf Raise', category: 'isolation', equipment: 'machine', movementPattern: 'isolation', defaultRepRangeMin: 12, defaultRepRangeMax: 20, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-calves', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-seated-calf', name: 'Seated Calf Raise', category: 'isolation', equipment: 'machine', movementPattern: 'isolation', defaultRepRangeMin: 12, defaultRepRangeMax: 20, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-calves', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-good-morning', name: 'Good Morning', category: 'compound', equipment: 'barbell', movementPattern: 'hip_hinge', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-hamstrings', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-lower-back', role: 'primary', contribution: 0.7 }, { muscleGroupId: 'mg-glutes', role: 'secondary', contribution: 0.5 }] },

  // --- CORE ---
  { id: 'ex-plank', name: 'Plank', category: 'isolation', equipment: 'bodyweight', movementPattern: 'isolation', defaultRepRangeMin: 30, defaultRepRangeMax: 60, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-abs', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-obliques', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-cable-crunch', name: 'Cable Crunch', category: 'isolation', equipment: 'cable', movementPattern: 'isolation', defaultRepRangeMin: 12, defaultRepRangeMax: 20, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-abs', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-hanging-leg-raise', name: 'Hanging Leg Raise', category: 'isolation', equipment: 'bodyweight', movementPattern: 'isolation', defaultRepRangeMin: 8, defaultRepRangeMax: 15, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-abs', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-obliques', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-ab-wheel', name: 'Ab Wheel Rollout', category: 'isolation', equipment: 'bodyweight', movementPattern: 'isolation', defaultRepRangeMin: 8, defaultRepRangeMax: 15, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-abs', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-woodchop', name: 'Cable Woodchop', category: 'isolation', equipment: 'cable', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-obliques', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-abs', role: 'secondary', contribution: 0.4 }] },

  // --- ADDITIONAL COMPOUND ---
  { id: 'ex-pendlay-row', name: 'Pendlay Row', category: 'compound', equipment: 'barbell', movementPattern: 'horizontal_pull', defaultRepRangeMin: 5, defaultRepRangeMax: 8, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-upper-back', role: 'primary', contribution: 0.9 }, { muscleGroupId: 'mg-lats', role: 'primary', contribution: 0.6 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-chest-supported-row', name: 'Chest Supported Row', category: 'compound', equipment: 'dumbbell', movementPattern: 'horizontal_pull', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-upper-back', role: 'primary', contribution: 0.9 }, { muscleGroupId: 'mg-lats', role: 'secondary', contribution: 0.5 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-sumo-deadlift', name: 'Sumo Deadlift', category: 'compound', equipment: 'barbell', movementPattern: 'hip_hinge', defaultRepRangeMin: 3, defaultRepRangeMax: 6, defaultRestSeconds: 240, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 0.6 }, { muscleGroupId: 'mg-glutes', role: 'primary', contribution: 0.9 }, { muscleGroupId: 'mg-hamstrings', role: 'secondary', contribution: 0.5 }, { muscleGroupId: 'mg-lower-back', role: 'secondary', contribution: 0.5 }] },
  { id: 'ex-db-rdl', name: 'Dumbbell Romanian Deadlift', category: 'compound', equipment: 'dumbbell', movementPattern: 'hip_hinge', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-hamstrings', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-glutes', role: 'primary', contribution: 0.7 }] },
  { id: 'ex-machine-chest-press', name: 'Machine Chest Press', category: 'compound', equipment: 'machine', movementPattern: 'horizontal_push', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-chest', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-machine-shoulder-press', name: 'Machine Shoulder Press', category: 'compound', equipment: 'machine', movementPattern: 'vertical_push', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 120, muscles: [{ muscleGroupId: 'mg-front-delts', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-triceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-machine-row', name: 'Machine Row', category: 'compound', equipment: 'machine', movementPattern: 'horizontal_pull', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-upper-back', role: 'primary', contribution: 0.8 }, { muscleGroupId: 'mg-lats', role: 'secondary', contribution: 0.6 }, { muscleGroupId: 'mg-biceps', role: 'secondary', contribution: 0.3 }] },
  { id: 'ex-smith-squat', name: 'Smith Machine Squat', category: 'compound', equipment: 'machine', movementPattern: 'squat', defaultRepRangeMin: 8, defaultRepRangeMax: 12, defaultRestSeconds: 150, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 1.0 }, { muscleGroupId: 'mg-glutes', role: 'secondary', contribution: 0.6 }] },
  { id: 'ex-goblet-squat', name: 'Goblet Squat', category: 'compound', equipment: 'dumbbell', movementPattern: 'squat', defaultRepRangeMin: 8, defaultRepRangeMax: 15, defaultRestSeconds: 90, muscles: [{ muscleGroupId: 'mg-quads', role: 'primary', contribution: 0.9 }, { muscleGroupId: 'mg-glutes', role: 'secondary', contribution: 0.5 }] },
  { id: 'ex-concentration-curl', name: 'Concentration Curl', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-biceps', role: 'primary', contribution: 1.0 }] },
  { id: 'ex-kickback', name: 'Tricep Kickback', category: 'isolation', equipment: 'dumbbell', movementPattern: 'isolation', defaultRepRangeMin: 10, defaultRepRangeMax: 15, defaultRestSeconds: 60, muscles: [{ muscleGroupId: 'mg-triceps', role: 'primary', contribution: 1.0 }] },
];
